# ChirpStack v4 Configuration

[logging]
level = "info"

[postgresql]
dsn = "postgres://airquality:airquality@timescaledb/airquality?sslmode=disable"
max_open_connections = 10
min_idle_connections = 0

[redis]
servers = ["redis://redis:6379/"]

[network]
net_id = "000000"
enabled_regions = ["eu868"]

[api]
bind = "0.0.0.0:8080"
secret = "you-must-replace-this"

[integration]
enabled = ["mqtt"]

  [integration.mqtt]
  event_topic = "application/{{application_id}}/device/{{dev_eui}}/event/{{event}}"
  command_topic = "application/{{application_id}}/device/{{dev_eui}}/command/{{command}}"
  json = true
  server = "tcp://mosquitto:1883"
  qos = 0
  clean_session = true
  client_id = ""
