; PlatformIO Project Configuration File
; TripoliLabs Air Quality Monitoring - Firmware
; Target: Heltec LoRa32 V3 ESP32-S3

[platformio]
default_envs = heltec_lora32_v3_debug

[env:heltec_lora32_v3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = espidf

; Serial monitor
monitor_speed = 115200

; Upload over USB
upload_protocol = esptool
upload_speed = 921600

; Library dependencies
lib_compat_mode = off
lib_deps =
    https://github.com/boschsensortec/BME280_SensorAPI.git
    jgromes/RadioLib@^7.5.0
    
[env:heltec_lora32_v3_debug]
extends = env:heltec_lora32_v3
build_type = debug

[env:heltec_lora32_v3_release]
extends = env:heltec_lora32_v3
build_type = release
